parameters:
#    symplefy_frontend.example.class: fabsalito\symplefy\FrontendBundle\Example

services:
#    symplefy_frontend.example:
#        class: %symplefy_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    symplefy_frontend_main.menu_builder:
        class: fabsalito\symplefy\FrontendBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    symplefy_frontend_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: symplefy_frontend_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu