parameters:
#    symplefy_frontend.example.class: fabsalito\symplefy\FrontendBundle\Example

services:
#    symplefy_frontend.example:
#        class: %symplefy_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
