parameters:
    finance.default.class: fabsalito\FinanceBundle\Controller\DefaultController

services:
     finance.default:
        class: %finance.default.class%
#        arguments: [@service_id, "plain_value", %parameter%]