#fabsalito_finance:
#    resource: "@fabsalitoFinanceBundle/Resources/config/routing.yml"
#    prefix:   /

#fabsalito_geo:
#    resource: "@fabsalitoGeoBundle/Resources/config/routing.yml"
#    prefix:   /

symplefy_backend:
    resource: "@SymplefyBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

symplefy_frontend:
    resource: "@SymplefyFrontendBundle/Resources/config/routing.yml"
    prefix:   /

