parameters:
#    fabsalito_geo.example.class: fabsalito\GeoBundle\Example

services:
#    fabsalito_geo.example:
#        class: %fabsalito_geo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
