parameters:
    fabsalito_geo.default.class: fabsalito\GeoBundle\Controller\DefaultController

services:
     fabsalito_geo.default:
        class: %fabsalito_geo.default.class%
#        arguments: [@service_id, "plain_value", %parameter%]