parameters:
#    budget.example.class: fabsalito\BudgetBundle\Example

services:
#    budget.example:
#        class: %budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
